baseurl = "https://hayorov.me/"
languageCode = "en"
title = "Alex Khaerov"
theme = "hyde-hyde"
enableRobotsTXT = "true"
disqusShortname = "alexkhaerov"

[params]
author = "Alex Khaerov "
title = ""
since = "2019"
authorimage = "/ava_with_bike.png"
description = """Alex Khaerov"""
highlightjs = true
highlightjsstyle = "github"
showBuiltWith = false
copyright = "Alex Khaerov"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
ga4_id = "G-757Y123ZRP"

[params.social]
linkedin = "alexkhaerov"
twitter = "hayorov"
github = "hayorov"
medium = "akhaerov"
gravatar = "i@hayorov.me"

[sitemap]
ChangeFreq = "weekly"
Priority = ".7"

## Main Menu
[[menu.main]]
name = "ğŸ“ Blog Posts"
weight = 40
identifier = "posts"
url = "/posts"

[[menu.main]]
name = "ğŸ‘¤ About Me"
identifier = "about"
weight = 10
url = "/about"

[[menu.main]]
name = "ğŸ¤ My Talks"
identifier = "talks"
weight = 20
url = "/talks"

[[menu.main]]
name = "ğŸ“š Publications"
identifier = "publications"
weight = 30
url = "/publications"

[[menu.main]]
name = "ğŸ›¸ FPV & UAV"
identifier = "fpv"
weight = 15
url = "/fpv"

[[menu.main]]
name = "ğŸš´â€â™‚ï¸ Cycling"
identifier = "cycling"
weight = 16
url = "/cycling"

[[menu.main]]
name = "ğŸ¦ "
weight = 100
identifier = "covid"
url = "/posts/covid-signs"
