baseurl = "https://hayorov.me/"
languageCode = "en"

title = ""
theme = "hyde-hyde"

googleAnalytics = "UA-156069333-1"
enableRobotsTXT = "true"

[params]
    author = "Alex Khaerov "
    title = ""
    since = "2019"
    authorimage = "/ava_with_bike.png"
    description = """Alex Khaerov"""
    highlightjs = true
    highlightjsstyle = "github"
    showBuiltWith = false
    copyright = "Alex Khaerov"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

[params.social]
    linkedin = "alexkhaerov"
	twitter = "hayorov"
	github = "hayorov"
    telegram = "hayorov"
    medium = "hayorov"
    email = "i@hayorov.me"
    keybase = "hayorov"
    instagram = "hayorov"

[sitemap]
  ChangeFreq = "weekly"
  Priority = ".7"

## Main Menu
[[menu.main]]
    name = "ðŸ¦  signs"
    weight = 100
    identifier = "covid"
    url = "/posts/covid-signs"

[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 10
    url = "/about"

[[menu.main]]
    name = "My Talks"
    identifier = "talks"
    weight = 20
    url = "/talks"

[[menu.main]]
    name = "Publications"
    identifier = "publications"
    weight = 30
    url = "/publications"

[[menu.main]]
    name = "Blog Posts"
    weight = 40
    identifier = "posts"
    url = "/posts"
